### ISSUE TITLE
Can not be autoloaded using composer

### ISSUE THREAD

**Issue by DanielRuf** [badoo/soft-mocks#41]
As there is not `autoload` entry in composer.json the `autoload_*` files of composer do not include `\Badoo\SoftMocks` at all.

Adding the following should fix this:

```
  "autoload": {
    "classmap": [
        "src/Badoo/"
    ]
  },
```

**Comment by YuriyNasretdinov** [comment]
From my understading the reason why Soft Mocks classes are not autoloaded (and why the whole SoftMocks is implemented as a single file too) is because Soft Mocks classes should be called _before_ autoload even starts to function. If you are able to autoload Soft Mocks classes, it is already too late as there are probably already some classes loaded that haven't been rewritten by Soft Mocks which means that they won't be mocked.

**Comment by DanielRuf** [comment]
My use case was that I loaded SoftMocks (first) and needed a full composer integration with its autoloader.

**Comment by YuriyNasretdinov** [comment]
Composer autoload needs to rewrite files using Soft Mocks, otherwise it won't work which means there is no way it autoload code using itself sadly.

**Comment by DanielRuf** [comment]
I am aware of that =) I did not say that I load mocked classes via composer. And I do not exactly know anymore but I think it worked in my use case.

If it uses composer.json it makes sense to add the `autoload` entry to it.

**Comment by DanielRuf** [comment]
https://github.com/badoo/soft-mocks/blob/master/composer.json
